### ISSUE TITLE
can‘t unzip pre-trained model

### ISSUE THREAD

**Issue by PP-dog** [jfzhang95/pytorch-deeplab-xception#111]
I download pretrained model of Resnet, but can't unzip it

**Comment by jt78kim** [comment]
I have same problem.
It says that it doesn't look like a tar archive.

============================================
(base) [jtkim@salmon Downloads]$ tar xfv deeplab-drn.pth.tar 
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
============================================

**Comment by zhaowt61** [comment]
no need to unzip, just remove the exention ".tar'.
